/*
 * Copyright (C) 2025 FairPhone B.V.
 *
 * SPDX-FileCopyrightText: 2025. FairPhone B.V.
 *
 * SPDX-License-Identifier: EUPL-1.2
 */

package com.fairphone.spring.launcher.ui.theme

import androidx.compose.ui.graphics.Color

val Color_FP_Brand_Sand = Color(0xFFC3D1D0)
val Color_FP_Brand_Forest = Color(0xFF00433D)
val Color_FP_Brand_Lime = Color(0xFFD8FF4F)
val Color_Orange = Color(0xFFFFB14E)
val Color_Google_Work_Profile = Color(0xFF4285F4)

val errorColor = Color(0xFFD84D4D)
val onErrorColor = Color(0xFFFFFFFF)

val primaryLight = Color(0xFF006A61)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF141414)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF7B580D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFFFFF)
val onSecondaryContainerLight = Color(0xFF141414)
val tertiaryLight = Color(0xFF46617A)
val onTertiaryLight = Color(0xFFCCCED4)
val tertiaryContainerLight = Color(0xFFCACED7)
val onTertiaryContainerLight = Color(0xFF2E4961)
val errorLight = Color(0xFFE24343)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDBD1)
val onErrorContainerLight = Color(0xFF723522)
val backgroundLight = Color(0xFFCED3DC)
val onBackgroundLight = Color(0xFF141414)
val surfaceLight = Color(0x4DFFFFFF)
val onSurfaceLight = Color(0xFF141414)
val surfaceVariantLight = Color(0xB2FFFFFF)
val onSurfaceVariantLight = Color(0xFF505050)
val outlineLight = Color(0xFFEAECF1)
val outlineVariantLight = Color(0xFF4E4E4E)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3133)
val inverseOnSurfaceLight = Color(0xFFECF2F3)
val inversePrimaryLight = Color(0xFF82D5CA)
val surfaceDimLight = Color(0xFFCACED7)
val surfaceBrightLight = Color(0xFFF5FAFB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F6)
val surfaceContainerLight = Color(0xFFE8E8EA)
val surfaceContainerHighLight = Color(0xFFE3E9EA)
val surfaceContainerHighestLight = Color(0xFFDEE3E5)

val primaryDark = Color(0xFF82D5CA)
val onPrimaryDark = Color(0xFF003732)
val primaryContainerDark = Color(0xFFFFFFFF)
val onPrimaryContainerDark = Color(0xFF001A17)
val secondaryDark = Color(0xFFEEBF6D)
val onSecondaryDark = Color(0xFF422C00)
val secondaryContainerDark = Color(0x1AFFFFFF)
val onSecondaryContainerDark = Color(0xFFFFFFFF)
val tertiaryDark = Color(0xFFAEC9E6)
val onTertiaryDark = Color(0xFF141414)
val tertiaryContainerDark = Color(0xFF0F0F0F)
val onTertiaryContainerDark = Color(0xFFCDE5FF)
val errorDark = Color(0xFFE24343)
val onErrorDark = Color(0xFF561F0E)
val errorContainerDark = Color(0xFF723522)
val onErrorContainerDark = Color(0xFFFFDBD1)
val backgroundDark = Color(0xFF000000)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0x333B3B3B)
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0x803B3B3B)
val onSurfaceVariantDark = Color(0xFFCCCCCC)
val outlineDark = Color(0xFF2D2D2D)
val outlineVariantDark = Color(0xFF000000)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E5)
val inverseOnSurfaceDark = Color(0xFF2B3133)
val inversePrimaryDark = Color(0xFF006A61)
val surfaceDimDark = Color(0xFF000000)
val surfaceBrightDark = Color(0xFF343A3B)
val surfaceContainerLowestDark = Color(0xFF090F10)
val surfaceContainerLowDark = Color(0xFF171D1E)
val surfaceContainerDark = Color(0xFF222222)
val surfaceContainerHighDark = Color(0xFF252B2C)
val surfaceContainerHighestDark = Color(0xFF303637)

val onBoardingLightDescription = Color(0xff767676)
val homeButtonBackgroundDarkColor = Color(0xFF292928)
val homeButtonBackgroundLightColor = Color(0xffeff0f2)

val backgroundShapeBackgroundLightStart = Color(0x88E0E7F2)
val backgroundShapeBorderLightStart = Color(0x99999999)
val backgroundShapeBackgroundDarkStart = Color(0xff1F1F1F)
val backgroundShapeBorderDarkStart = Color(0x33666666)

val modeButtonBackgroundLight = Color(0x55FFFFFF)
val actionButtonBackgroundLight = Color(red = 255, green = 255, blue = 255, alpha = 30)
val actionButtonStrokeLight = Color(0x55FFFFFF)
val selectedActionButtonBackgroundLight = Color(red = 255, green = 255, blue = 255, alpha = 50)
val selectedActionButtonStrokeEndGradientLight = Color(red = 255, green = 255, blue = 255, alpha = 55)
val focusActionButtonStrokeLight = Color(0xFF141414)
val pressedActionButtonStartGradienLight = Color(red = 94, green = 94, blue = 94, alpha = 60)
val pressedActionButtonEndGradienLight = Color(red = 255, green = 255, blue = 255, alpha = 30)

val modeButtonBackgroundDark = Color(red = 59, green = 59, blue = 59, alpha = 30)
val modeButtonColorStaticDarkWallpaper = Color(0x2B979797)
val actionButtonBackgroundDark = Color(red = 59, green = 59, blue = 59, alpha = 50)
val actionButtonStrokeDark = Color(0x22CCCCCC)
val selectedActionButtonBackgroundDark = Color(red = 255, green = 255, blue = 255, alpha = 50)
val selectedActionButtonStrokeEndGradientDark = Color(0x01999999)
val focusActionButtonStrokeDark = Color(0xFFFFFFFF)
val pressedActionButtonStartGradienDark = Color(red = 255, green = 255, blue = 255, alpha = 10)
val pressedActionButtonEndGradienDark = Color(red = 59, green = 59, blue = 59, alpha = 30)

val switchBorderStartLightColor = Color(0xFFC3C3C3)
val switchBorderEndLightColor = Color.White
val switchBackgroundLightColor = Color(0x33CCCCCC)
val switchBorderStartDarkColor = Color(0xFF303030)
val switchBorderEndDarkColor = Color(0xFF696969)
val switchBackgroundDarkColor = Color(0x33CCCCCC)
val switchThumbColor = Color(0xFF141414)
val switchCheckedBackground = Color_FP_Brand_Lime

val brandAccentLight = Color(0xFF556423)
val onBrandAccentLight = Color(0xFFFFFFFF)
val brandAccentContainerLight = Color(0xFFD9EB9A)
val onBrandAccentContainerLight = Color(0xFF3E4C0B)

val brandAccentLightMediumContrast = Color(0xFF2E3B00)
val onBrandAccentLightMediumContrast = Color(0xFFFFFFFF)
val brandAccentContainerLightMediumContrast = Color(0xFF647330)
val onBrandAccentContainerLightMediumContrast = Color(0xFFFFFFFF)

val brandAccentLightHighContrast = Color(0xFF263000)
val onBrandAccentLightHighContrast = Color(0xFFFFFFFF)
val brandAccentContainerLightHighContrast = Color(0xFF414F0E)
val onBrandAccentContainerLightHighContrast = Color(0xFFFFFFFF)

val brandAccentDark = Color(0xFFBDCE80)
val onBrandAccentDark = Color(0xFF293500)
val brandAccentContainerDark = Color(0xFF3E4C0B)
val onBrandAccentContainerDark = Color(0xFFD9EB9A)

val brandAccentDarkMediumContrast = Color(0xFFD2E594)
val onBrandAccentDarkMediumContrast = Color(0xFF202900)
val brandAccentContainerDarkMediumContrast = Color(0xFF879850)
val onBrandAccentContainerDarkMediumContrast = Color(0xFF000000)

val brandAccentDarkHighContrast = Color(0xFFE6F8A6)
val onBrandAccentDarkHighContrast = Color(0xFF000000)
val brandAccentContainerDarkHighContrast = Color(0xFFB9CA7D)
val onBrandAccentContainerDarkHighContrast = Color(0xFF080D00)

